# SPDX-FileCopyrightText: 2026 The Catabolic Contributors
# SPDX-License-Identifier: MIT

"""Deterministic schema/reference generation; released artifacts are read-only."""

import hashlib
import json
from importlib.resources import files

from ..domain import CatabolicError
from . import v1, v2, v3

VERSION = v3.VERSION
SCHEMA_ID = v3.SCHEMA_ID


def model(version):
    if version not in (1, 2, 3):
        raise CatabolicError("unsupported manifest version")
    return {1: v1, 2: v2, 3: v3}[version]


def schema(version=VERSION):
    profile = model(version)
    value = profile.Document.model_json_schema()
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": profile.SCHEMA_ID,
        **value,
    }


def schema_text(version=VERSION):
    return (
        json.dumps(schema(version), indent=2, sort_keys=True, ensure_ascii=False) + "\n"
    )


def _type(field):
    if "$ref" in field:
        return field["$ref"].rsplit("/", 1)[-1]
    if "anyOf" in field:
        return " or ".join(_type(branch) for branch in field["anyOf"])
    if field.get("type") == "array":
        return "array of " + _type(field["items"])
    return field.get("type", "JSON")


def reference_text(version=VERSION):
    value = schema(version)
    lines = [
        f"# Open Catalog: Catabolic manifest v{version} field reference",
        "",
        "Generated from annotated Python models. Do not edit this file by hand.",
        "",
        f"Schema ID: `{model(version).SCHEMA_ID}`. JSON Schema Draft 2020-12.",
        "",
        "This is a catalog projection profile, not a complete database backup. See OPEN_CATALOG.md for identity, integrity, preservation, and versioning rules.",
        "",
        "Every record preserves unknown JSON fields. All listed fields are required unless marked otherwise; nullable means null is accepted, not that the field may be omitted.",
    ]
    records = {"Document": value, **value.get("$defs", {})}
    for name, record in records.items():
        if "properties" not in record:
            continue
        lines += [
            "",
            f"## {name}",
            "",
            record.get("description", ""),
            "",
            "| Field | Type | Required | Since | Deprecated | Description |",
            "| --- | --- | --- | --- | --- | --- |",
        ]
        for key, field in record["properties"].items():
            description = (
                field.get("description", "").replace("|", "\\|").replace("\n", " ")
            )
            if "examples" in field:
                description += (
                    " Examples: "
                    + json.dumps(field["examples"], ensure_ascii=False).replace(
                        "|", "\\|"
                    )
                    + "."
                )
            lines.append(
                f"| `{key}` | {_type(field)} | {'yes' if key in record.get('required', []) else 'no'} | {field.get('x-since', VERSION)} | {'yes' if field.get('deprecated') else 'no'} | {description} |"
            )
    return "\n".join(lines) + "\n"


def changes(before, after, path=""):
    """Structural diff only; arbitrary JSON Schema compatibility is not inferred."""
    if type(before) is not type(after):
        return [path or "/"]
    if isinstance(before, dict):
        found = []
        for key in sorted(before.keys() | after.keys()):
            pointer = path + "/" + key.replace("~", "~0").replace("/", "~1")
            found.extend(
                [pointer]
                if key not in before or key not in after
                else changes(before[key], after[key], pointer)
            )
        return found
    return [] if before == after else [path or "/"]


def check_release():
    root = files("catabolic.interchange").joinpath("releases")
    lock = json.loads(root.joinpath("index.json").read_text())
    for version in (1, 2, 3):
        release = root.joinpath(f"manifest-v{version}.schema.json").read_text()
        reference = root.joinpath(f"manifest-v{version}.md").read_text()
        for name, text in [
            (f"manifest-v{version}.schema.json", release),
            (f"manifest-v{version}.md", reference),
        ]:
            if hashlib.sha256(text.encode()).hexdigest() != lock[name]:
                raise CatabolicError(f"frozen release artifact changed: {name}")
        changed = changes(json.loads(release), schema(version))
        if changed or reference != reference_text(version):
            raise CatabolicError(
                f"models differ from frozen v{version}; review a new format version rather than rewriting v{version}"
            )
    return {
        "compatible": True,
        "format_version": VERSION,
        "schema_id": SCHEMA_ID,
        "generated_artifacts_match": True,
    }
