"""Deterministic schema/reference generation; released artifacts are read-only."""

import hashlib
import json
from importlib.resources import files

from ..domain import CatabolicError
from .v1 import SCHEMA_ID, VERSION, Document


def schema():
    value = Document.model_json_schema()
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": SCHEMA_ID,
        **value,
    }


def schema_text():
    return json.dumps(schema(), indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def _type(field):
    if "$ref" in field:
        return field["$ref"].rsplit("/", 1)[-1]
    if "anyOf" in field:
        return " or ".join(_type(branch) for branch in field["anyOf"])
    if field.get("type") == "array":
        return "array of " + _type(field["items"])
    return field.get("type", "JSON")


def reference_text():
    value = schema()
    lines = [
        "# Open Catalog: Catabolic manifest v1 field reference",
        "",
        "Generated from annotated Python models. Do not edit this file by hand.",
        "",
        f"Schema ID: `{SCHEMA_ID}`. JSON Schema Draft 2020-12.",
        "",
        "This is a catalog projection profile, not a complete database backup. See OPEN_CATALOG.md for identity, integrity, preservation, and versioning rules.",
        "",
        "Every record preserves unknown JSON fields. All listed fields are required unless marked otherwise; nullable means null is accepted, not that the field may be omitted.",
    ]
    records = {"Document": value, **value.get("$defs", {})}
    for name, record in records.items():
        if "properties" not in record:
            continue
        lines += [
            "",
            f"## {name}",
            "",
            record.get("description", ""),
            "",
            "| Field | Type | Required | Since | Deprecated | Description |",
            "| --- | --- | --- | --- | --- | --- |",
        ]
        for key, field in record["properties"].items():
            description = (
                field.get("description", "").replace("|", "\\|").replace("\n", " ")
            )
            if "examples" in field:
                description += (
                    " Examples: "
                    + json.dumps(field["examples"], ensure_ascii=False).replace(
                        "|", "\\|"
                    )
                    + "."
                )
            lines.append(
                f"| `{key}` | {_type(field)} | {'yes' if key in record.get('required', []) else 'no'} | {field.get('x-since', VERSION)} | {'yes' if field.get('deprecated') else 'no'} | {description} |"
            )
    return "\n".join(lines) + "\n"


def changes(before, after, path=""):
    """Structural diff only; arbitrary JSON Schema compatibility is not inferred."""
    if type(before) is not type(after):
        return [path or "/"]
    if isinstance(before, dict):
        found = []
        for key in sorted(before.keys() | after.keys()):
            pointer = path + "/" + key.replace("~", "~0").replace("/", "~1")
            found.extend(
                [pointer]
                if key not in before or key not in after
                else changes(before[key], after[key], pointer)
            )
        return found
    return [] if before == after else [path or "/"]


def check_release():
    root = files("catabolic.interchange").joinpath("releases")
    release = root.joinpath("manifest-v1.schema.json").read_text()
    reference = root.joinpath("manifest-v1.md").read_text()
    lock = json.loads(root.joinpath("index.json").read_text())
    for name, text in [
        ("manifest-v1.schema.json", release),
        ("manifest-v1.md", reference),
    ]:
        if hashlib.sha256(text.encode()).hexdigest() != lock[name]:
            raise CatabolicError(f"frozen release artifact changed: {name}")
    changed = changes(json.loads(release), schema())
    if changed or reference != reference_text():
        raise CatabolicError(
            "models differ from frozen v1; review a new format version rather than rewriting v1"
        )
    return {
        "compatible": True,
        "format_version": VERSION,
        "schema_id": SCHEMA_ID,
        "generated_artifacts_match": True,
    }
