[package]
name = "catabolic-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "catabolic-native"
path = "src/main.rs"

[dependencies]
catabolic-core.workspace = true
catabolic-store.workspace = true
serde_json.workspace = true

[lints]
workspace = true
